//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Orders = new HashSet<Order>();
        }
    
        public int CId { get; set; }
        public string CName { get; set; }
        public string CPassword { get; set; }
        public string CEmail { get; set; }
        public string CAddress { get; set; }
        public string CPhone { get; set; }
        public byte[] CPicture { get; set; }
        public Nullable<int> VouId { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
