//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCondition
    {
        public int PCId { get; set; }
        public int PId { get; set; }
        public string PCondition1 { get; set; }
        public Nullable<int> PStock { get; set; }
        public Nullable<int> PSoldquantity { get; set; }
    }
}
