//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int PId { get; set; }
        public string PName { get; set; }
        public int PBasicPrice { get; set; }
        public int PCategoryId { get; set; }
        public int PStock { get; set; }
        public int PDiscount { get; set; }
        public string PDescription { get; set; }
        public byte[] PPicture { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Review { get; set; }
        public int PShopId { get; set; }
        public Nullable<int> MId { get; set; }
        public Nullable<int> PSoldQuantity { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
