//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public Voucher()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int VouId { get; set; }
        public string VouCode { get; set; }
        public int VouDiscount { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
